language: python
python:
  - "pypy3"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.9-dev"
  - "3.10-dev"
  - "nightly"

matrix:
  allow_failures:
    - python: "3.10-dev"
    - python: "nightly"

cache:
  directories:
    - $HOME/.cache/pip

install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - pip install typing-extensions
  - pip install -e .

script:
  - flake8 soco
  - flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
  - pylint soco
  - pytest --cov-config .coveragerc --cov soco .
  - if [ `python -c "from __future__ import print_function;import sys;print(int(sys.version_info.major==3 and sys.version_info.minor>=6 and sys.implementation.name == 'cpython'))"` -gt 0 ];then black --check soco tests;fi

after_script:
  - coveralls
